### PR TITLE
Remove hep

### PR DESCRIPTION
**Pull request by 0ctagon**
For now, every HEP plots has been reproduced with the new model functions.
(except the flatten, which cannot be reproduced as we cannot flatten the signal yet, will be corrected when PR about flatten will be merged)

Still need to rename every svg and tweak a bit the documentation.

### CODE REVIEW

**Comment by 0ctagon** [comment]
@cyrraz ready to be reviewed.

Maybe reading the doc here might be better: https://plothist.readthedocs.io/en/remove_hep/index.html
Lot of things change in 1d and model section.

**Comment by cyrraz** [comment]
@0ctagon There is a way to correct the order of the stacked components in the functions, but the user need to know how to do it themselves if the replot the legend later. I would add it in the documentation. This is how to do it:

```
# docs/img/model_with_stacked_and_unstacked_function_components.svg
# reverse the order of the two stacked entries in the legend
handles, labels = ax.get_legend_handles_labels()
order = [1,0,2]
ax.legend([handles[idx] for idx in order],[labels[idx] for idx in order])


# docs/img/ratio_data_vs_model_with_stacked_and_unstacked_function_components.svg
# reverse the order of the two stacked entries in the legend
handles, labels = ax.get_legend_handles_labels()
order = [1,0,2,3,4]
ax.legend([handles[idx] for idx in order],[labels[idx] for idx in order])
```

**Comment by cyrraz** [comment]
> @0ctagon There is a way to correct the order of the stacked components in the `plot_model()` and `plot_data_model_comparison()` functions, but the user need to know how to do it themselves if they replot the legend outside of the functions. I would add it in the documentation. This is how to do it:
> 
> ```
> # docs/img/model_with_stacked_and_unstacked_function_components.svg
> # reverse the order of the two stacked entries in the legend
> handles, labels = ax.get_legend_handles_labels()
> order = [1,0,2]
> ax.legend([handles[idx] for idx in order],[labels[idx] for idx in order])
> 
> 
> # docs/img/ratio_data_vs_model_with_stacked_and_unstacked_function_components.svg
> # reverse the order of the two stacked entries in the legend
> handles, labels = ax.get_legend_handles_labels()
> order = [1,0,2,3,4]
> ax.legend([handles[idx] for idx in order],[labels[idx] for idx in order])
> ```

The internal fix is implemented in #83, but we should show the user in the doc how to tune the legend order in case the user call the legend function outside of `plot_model()` and `compare_data_mode()`

**Review by cyrraz — APPROVED** [review]
Great PR, I left 3 minor comments, please check them. We can then merge. If typos are left in the documentation, we will anyhow have additional passes through the documentation. FYI, there will be conflict for two figures with #81, but easy to fix

**Comment by cyrraz** [comment]
Hi @0ctagon, I merged the branch used for this PR in the branch used for #83, please merge first this one and the the other one

**Pull request merged**
